### PR TITLE
SFR-1752: Remove rspec workflow

### PR DESCRIPTION
**Pull request by clarissarichard**
[Jira Ticket](http://jira.nypl.org/browse/SFR-1752)

### This PR does the following:
- Removed Rspec workflow in favor of the Cucumber/Playwright workflow

### Testing requirements & instructions: 
-  Run Playwright tests and all tests pass

### CODE REVIEW

**Comment by samanthaandrews** [comment]
Potentially annoying drive-by comment but as a hint you'll just need to remove the `.github/workflows/rspec-integration-tests.yml` file to ensure these tests no longer run on our DRB CI! Lmk if you need me to also remove any secrets that were being used in that file and I will do so in the GitHub admin interface.

**Comment by clarissarichard** [comment]
Please let me know if this will be released in 0.17.5 instead, and I can move my entry in the changelog!

**Comment by ayan1229** [comment]
@clarissarichard yes, let's add it to this release.

**Review by ayan1229 — APPROVED** [review]
🚀

**Review by samanthaandrews — APPROVED** [review]

**Pull request merged**
