### PR TITLE
NO-REF releasing 8.2

### PR DESCRIPTION
**Pull request by hokei**
No Jira Ticket

### This PR does the following:
- Bumps package and changelog for release

### Testing requirements & instructions: 
-

### CODE REVIEW

**Comment by hokei** [comment]
shouldn't this be pushed automatically with tag?  Is there something else we need to set up that isn't set up?

**Comment by hokei** [comment]
(I think maybe I forgot to commit before pushing the tag)

**Comment by mwbenowitz** [comment]
Yeah, you have to bump the version manually, I don't know of any integration that can do it automatically

**Comment by hokei** [comment]
Yeah I think what I did was deploy without these bumps ... will remember for next time
or bring up a checklist haha

**Pull request merged**
