### PR TITLE
Sfr 415 loading

### PR DESCRIPTION
**Pull request by nachocs**
Added reducers and action for loading, 
Loading spinner as in design, 
interceptor for http requests, 
added a class for the store to load it from anywhere, 
removed window.onload as it's not needed, 
and changed the index.ejs template to load react after preloadedstate just in case

### CODE REVIEW

**Comment by seanredmond** [comment]
I feel like it's out of place. My eyes are looking at the list of results, so I kind of want it centered there. (Maybe that's just centered in the window?)

Screen Shot 2019-05-23 at 11 41 38 AM

**Comment by mwbenowitz** [comment]
Looks/works good to me! I'm unsure about moving it down, I think centering it over the results section makes sense, but ensuring that it remains anchored there seems much harder than fixing it in the center of the window as it is now.

**Comment by seanredmond** [comment]
@mwbenowitz Do you see it centered in the window (horizontally _and_ vertically)? I see it centered horizontally but close to the top of the window

**Comment by mwbenowitz** [comment]
@seanredmond You're right, it looks correct when the window is wider than it is tall, but when flipped it does appear too far to the top of the screen

**Comment by nachocs** [comment]
I changed it to lower vertically

**Comment by mwbenowitz** [comment]
Looks better to me in the new position. It seems to appear off screen in mobile, but I don't think we're designing/building this for mobile at this point?

Has my approval once Sean signs off on the new position and potential addition of tests?

**Comment by nachocs** [comment]
Added test

**Comment by nachocs** [comment]
Solved merge conflicts

**Pull request merged**
